version: "3.9"
services:
  config-server:
    container_name: config-server    
    build:
      context: ./00-microservicio-config-server
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    restart: always
    networks:
      - red_microservicios
  eureka-server:
    container_name: eureka-server    
    build:
      context: ./01-microservicio-eureka-server
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - red_microservicios          
  gateway-server:
    container_name: gateway-server    
    build:
      context: ./02-microservicio-gateway-server-filter
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - eureka-server
      - config-server
    networks:
      - red_microservicios    
##este no tiene puerto fijo      
  servicio-alumnos:
    container_name: servicio-alumnos
    build:
      context: ./AB-servicio-alumnos
      dockerfile: ./Dockerfile    
    restart: always
    depends_on:
      - eureka-server
      - config-server
      - gateway-server
    networks:
      - red_microservicios   
##este no tiene puerto fijo      
  servicio-cursos:
    container_name: servicio-cursos
    build:
      context: ./AB-servicio-cursos
      dockerfile: ./Dockerfile    
    restart: always
    depends_on:
      - eureka-server
      - config-server
      - gateway-server
      - servicio-alumnos
    networks:
      - red_microservicios          
      
networks:
  red_microservicios:          