server:
  port: 8090
##ESTE TIENE PRIORIDAD SOBRE EL APPCONFIG
resilience4j:
  circuitbreaker:
    configs:
      nombreconfiguracion:    ##nombre que le doy a esta configuracion
        sliding-window-size: 6  ##tamaño de ventana
        failure-rate-threshold: 50 ##porcentaje de error
        wait-duration-in-open-state: 20s ##tiempo que queda abierto el circuito
        permitted-number-of-calls-in-half-open-state: 4 ##llamadas en estado semiabierto
        slow-call-rate-threshold: 50 ##porcentaje de llamadas lentas
        slow-call-duration-threshold: 5s ##tiempo limite
    instances:
      productos: ##lo vamos a usar en el microservicio productos
        base-config: nombreconfiguracion   
  timelimiter: ##para los limites de tiempo
    configs:
      nombreconfiguracion:
        timeout-duration: 5s
    instances:
      productos:   ##lo vamos a usar en el microservicio productos
        base-config: nombreconfiguracion  
spring:
  application:
    name: gateway-server
    ##para Sleuth/Zipkin saque todas las trazas, por defecto es un 10%,el endpoint lo configuro en el configserver
  sleuth:
    sampler:
      probability: 1.0  
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
  profiles:
    active:
    - dev            
  cloud:
    config:
##SIN DOCKER
      uri: http://config-server:8888
##CON DOCKER ,parece que sin docker¿? tambien va
##        uri: host.docker.internal:config-server