spring:
  application:
    name: spring-gateway-server
    ##para Sleuth/Zipkin saque todas las trazas, por defecto es un 10%,el endpoint lo configuro en el configserver
  sleuth:
    sampler:
      probability: 1.0  
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  config:
    import: 'optional:configserver::http://localhost:8888'
  profiles:
    active: dev